import { SignIn, SignInButton, SignOutButton, useUser } from '@clerk/nextjs'
import { type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime'

dayjs.extend(relativeTime)
import { api, type RouterOutputs } from '~/utils/api'
import Image from 'next/image'
import { LoadingPage } from '~/components/LoadingSpinner'
import { useState } from 'react'

// Keep things in one file until you are sure you need them elsewhere

const CreatePostWizard = () => {
  const { user } = useUser()
  const [input, setInput] = useState<string>('')
  const ctx = api.useContext()
  const { mutate, isLoading: isPosting } = api.posts.create.useMutation({
    onSuccess: () => {
      setInput('')
      void ctx.posts.getAll.invalidate()
    }
  })

  if (!user) return null

  return (
    <div className='mb-4 flex w-full gap-3 border-b border-slate-400'>
      <Image
        className='h-16 w-16 rounded-full'
        src={user.profileImageUrl}
        alt='profile image'
        width={64}
        height={64}
      />
      <input
        placeholder='Type some emojis'
        type='text'
        className='grow bg-transparent outline-none'
        value={input}
        onChange={e => setInput(e.target.value)}
        disabled={isPosting}
      />
      <button onClick={() => mutate({ content: input })}>Post</button>
    </div>
  )
}

type PostWithUser = RouterOutputs['posts']['getAll'][number]

const PostView = (props: PostWithUser) => {
  const { post, author } = props
  return (
    <div className='flex gap-3 border-b border-slate-400 p-4' key={post.id}>
      <Image
        src={author.profileImageUrl}
        alt={`${author.username}'s profile image`}
        className='h-10 w-10 rounded-full'
        width={40}
        height={40}
      />
      <div className='flex flex-col'>
        <div className='flex'>
          <span>{`@${author.username}`}</span>
          <span className='px-2'> · </span>
          <span className='text-gray-600'>
            {dayjs(post.createdAt).fromNow()}
          </span>
        </div>
        <span className='text-2xl'>{post.content}</span>
      </div>
    </div>
  )
}

const Feed = () => {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery()

  if (postsLoading) return <LoadingPage />

  return (
    <div className='flex flex-col space-y-2'>
      {data?.map(fullPost => (
        <PostView {...fullPost} key={fullPost.post.id} />
      ))}
    </div>
  )
}

const Home: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser()

  // start fetch early to use cached data later in the feed
  api.posts.getAll.useQuery()

  // return empty div when user nor posts have loaded
  if (!userLoaded) return <div></div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex justify-center'>
        <div className='h-screen w-full border-x border-slate-400 md:max-w-3xl '>
          <div className='border-b border-slate-400 p-4'>
            <div className='flex justify-between'>
              {!!isSignedIn && <CreatePostWizard />}

              <div className='grow text-sm text-gray-500'>
                {!isSignedIn && <SignInButton />}

                {isSignedIn && <SignOutButton />}
              </div>
            </div>
            <Feed />
          </div>
        </div>
      </main>
    </>
  )
}

export default Home
