import { SignIn, SignInButton, SignOutButton, useUser } from '@clerk/nextjs'
import { type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime'

dayjs.extend(relativeTime)
import { api, type RouterOutputs } from '~/utils/api'
import Image from 'next/image'

// Keep things in one file until you are sure you need them elsewhere

const CreatePostWizard = () => {
  const { user } = useUser()
  if (!user) return null

  return (
    <div className='flex w-full gap-3'>
      <Image
        className='h-16 w-16 rounded-full'
        src={user.profileImageUrl}
        alt='profile image'
        width={64}
        height={64}
      />
      <input
        placeholder='Type some emojis'
        type='text'
        className='grow bg-transparent outline-none'
      />
    </div>
  )
}

type PostWithUser = RouterOutputs['posts']['getAll'][number]

const PostView = (props: PostWithUser) => {
  const { post, author } = props
  return (
    <div className='flex gap-3 border-b border-slate-400 p-4' key={post.id}>
      <Image
        src={author.profileImageUrl}
        alt={`${author.username}'s profile image`}
        className='h-10 w-10 rounded-full'
        width={40}
        height={40}
      />
      <div className='flex flex-col'>
        <div className='flex'>
          <span>{`@${author.username}`}</span>
          <span className='px-1'> · </span>
          <span>`@{dayjs(post.createdAt).fromNow()}`</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  )
}

const Home: NextPage = () => {
  const user = useUser()
  const { data, isLoading } = api.posts.getAll.useQuery()

  // if (isLoading) return <div>Loading...</div>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex justify-center'>
        <div className='h-screen w-full border-x border-slate-400 md:max-w-3xl '>
          <div className='border-b border-slate-400 p-4'>
            <div className='flex justify-between'>
              {!!user.isSignedIn && <CreatePostWizard />}

              <div className='grow text-sm text-gray-500'>
                {!user.isSignedIn && <SignInButton />}

                {!!user.isSignedIn && <SignOutButton />}
              </div>
            </div>
          </div>
          <div className='flex flex-col space-y-2'>
            {data?.map(fullPost => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  )
}

export default Home
